name: simrs_mobile
description: "SIMRS Mapping Prototype (Flutter Android)"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # === STATE MANAGEMENT (simple & safe) ===
  provider: ^6.1.2

  # === FIREBASE (STORAGE ONLY) ===
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1

  # === BACKEND COMMUNICATION ===
  http: ^1.2.1

  # === UTILITIES ===
  intl: ^0.19.0

  shared_preferences: ^2.2.0  # ‚Üê ADD THIS LINE

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png