name: simrs_mobile
description: "SIMRS Mapping Prototype (Flutter Android)"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # === STATE MANAGEMENT (simple & safe) ===
  provider: ^6.1.2

  # === FIREBASE (STORAGE ONLY) ===
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0

  # === BACKEND COMMUNICATION ===
  http: ^1.2.1

  # === UTILITIES ===
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
